from crewai.tools import tool
import redis
from google import genai
from typing import List
import numpy as np
from dotenv import load_dotenv
import os
from pydantic import BaseModel

# Load environment variables from .env file
load_dotenv()

# Retrieve configuration from environment variables
MODEL = os.getenv("MODEL")
API_KEY = os.getenv("REDIS_API_KEY")
HOST = os.getenv("REDIS_HOST")
PORT = os.getenv("REDIS_PORT")
PASSWORD = os.getenv("REDIS_PASSWORD")
EMBEDDING_MODEL = os.getenv("EMBEDDING_MODEL")

# Initialize Gemini client for embeddings and generation
client = genai.Client(api_key=API_KEY)

# Connect to Redis database
redis_client = redis.Redis(host=HOST, port=PORT, decode_responses=False, username="default", password=PASSWORD)

# Define the input format for the tool using Pydantic
class LawQuery(BaseModel):
    query: str

def connect_redis():
    """Check Redis connection and return client instance if successful."""
    try:
        redis_client.ping()
        print("Connected to Redis successfully!")
        return redis_client
    except redis.exceptions.ConnectionError as e:
        print(f"Could not connect to Redis: {e}")
        return None

def generate_embedding(text: str):
    """
    Generate embedding vector for the input text using Gemini's embedding model.
    """
    response = client.models.embed_content(
        model=EMBEDDING_MODEL,
        contents=[text]
    )
    return response.embeddings[0].values

def cosine_similarity(vec1, vec2):
    """
    Compute cosine similarity between two vectors.
    """
    dot = np.dot(vec1, vec2)
    norm1 = np.linalg.norm(vec1)
    norm2 = np.linalg.norm(vec2)
    return dot / (norm1 * norm2) if norm1 and norm2 else 0.0

def search_relevant_sections(redis_client, query: str, top_k: int = 5):
    """
    Search for the top-k most relevant legal sections in Redis using cosine similarity.
    """
    query_embedding = np.array(generate_embedding(query), dtype=np.float32)
    relevant_sections = []

    # Iterate over all keys matching the legal documents pattern
    for key in redis_client.scan_iter("legal:*"):
        section = redis_client.hgetall(key)
        try:
            # Decode fields and convert embedding to numpy array
            section_data = {
                k.decode('utf-8'): v.decode('utf-8') if k.decode('utf-8') != "embedding" else v
                for k, v in section.items()
            }
            section_embedding = np.frombuffer(section_data["embedding"], dtype=np.float32)
            similarity = cosine_similarity(query_embedding, section_embedding)
            
            # Collect section metadata and similarity
            relevant_sections.append({
                "similarity": similarity,
                "text": section_data["text"],
                "title": section_data["section_title"],
                "section": section_data["section_number"]
            })
        except Exception as e:
            print(f"Error processing section {key}: {e}")
            continue

    # Sort by similarity score and return top-k sections
    sorted_sections = sorted(relevant_sections, key=lambda x: x["similarity"], reverse=True)
    return sorted_sections[:top_k]

@tool("Search sections and laws")
def generate_rag_response(input: LawQuery | str | dict) -> str:
    """
    Tool to generate a legal answer using Gemini and relevant law sections retrieved from Redis.

    Input:
        - LawQuery (Pydantic model) or plain string/dict containing legal query.

    Output:
        - Answer generated by Gemini based on relevant context.
    """
    query = input.query if isinstance(input, LawQuery) else str(input)
    if not isinstance(query, str):
        print(f"Error: Expected query to be a string, but got {type(query)}")
    
    # Connect to Redis
    r = connect_redis()
    
    # Retrieve relevant legal sections using semantic search
    sections = search_relevant_sections(r, query)

    # Build context for prompt using retrieved sections
    context = "\n\n".join([f"{sec['section']} - {sec['title']}:\n{sec['text']}" for sec in sections])

    # Create prompt for Gemini model
    prompt = f"""Answer the following legal query using the context provided section and return section number, section title and content applies.

    Query: {query}

    Context:
    {context}

    Answer:"""

    # Get model response
    response = client.models.generate_content(
        model=MODEL,
        contents=[prompt]
    )

    answer = response.text.strip()
    
    return answer
